-- M21 iter-04: the 26-collection structure artifact (Option A) — real prod DDL.
-- Sequences first (junction-table serial ids), then all 26 collection tables.
CREATE SEQUENCE IF NOT EXISTS directus.sequences_files_2_id_seq;
CREATE SEQUENCE IF NOT EXISTS directus.sequences_files_id_seq;
CREATE SEQUENCE IF NOT EXISTS directus.sequences_roles_id_seq;
CREATE SEQUENCE IF NOT EXISTS directus.sim_translations_id_seq;
CREATE SEQUENCE IF NOT EXISTS directus.simulations_library_categories_id_seq;
CREATE SEQUENCE IF NOT EXISTS directus.simulations_translations_id_seq;
CREATE SEQUENCE IF NOT EXISTS directus.skill_paths_curators_id_seq;
CREATE SEQUENCE IF NOT EXISTS directus.skill_paths_library_categories_id_seq;

-- The 9 captured content collections (real prod DDL):
CREATE TABLE directus.simulations (id uuid NOT NULL, status character varying(255) NOT NULL DEFAULT 'draft'::character varying, sort integer, user_created uuid, date_created timestamp with time zone, user_updated uuid, date_updated timestamp with time zone, title character varying(255) NOT NULL, slug character varying(255) DEFAULT NULL::character varying, public_description text, internal_context text, cover uuid, skills json, job_roles json, level integer, read_more_link text, assignment_template_link text, duration integer, short_description text, type character varying(255), tags json, public_landing_page_url character varying(255), language character varying(255) NOT NULL DEFAULT 'SIMULATION_LANGUAGE_ENGLISH'::character varying, organization_description text, private boolean DEFAULT false, tenant_id character varying(255) DEFAULT NULL::character varying, indexed boolean DEFAULT true, organization_name character varying(255), duration_type character varying(255) DEFAULT 'SIMULATION_DURATION_TYPE_SCENARIO'::character varying, library_category uuid, source_zip uuid, seo_metadata text, seo_title character varying(255), job_position uuid, available_languages json DEFAULT '["english","italian","spanish","german","french","dutch","japanese","portuguese"]'::json, ai_assistant boolean DEFAULT false, ai_prompt text);
CREATE TABLE directus.skill_paths (id uuid NOT NULL, status character varying(255) NOT NULL DEFAULT 'draft'::character varying, sort integer, user_created uuid, date_created timestamp with time zone, user_updated uuid, date_updated timestamp with time zone, title character varying(255) NOT NULL, cover uuid, level integer NOT NULL, duration integer, description text, offered_by character varying(255), image uuid, curators_description text, slug character varying(255), chapter_list json, private boolean DEFAULT false, tenant_id uuid, video uuid, dark_mode boolean DEFAULT true, legacy_roles json, prerequisites json, public_landing_page_url character varying(255), seo_metadata text, seo_title character varying(255), indexed boolean DEFAULT true, require_all_ai_sim_pass_to_complete_skill_path boolean DEFAULT true);
CREATE TABLE directus.resource (id uuid NOT NULL, status character varying(255) NOT NULL DEFAULT 'draft'::character varying, user_created uuid, date_created timestamp with time zone, user_updated uuid, date_updated timestamp with time zone, type character varying(30) NOT NULL, title character varying(255), description text, duration integer, level integer NOT NULL DEFAULT 1, url text, youtube_video_id character varying(30), image uuid, tags json, youtube_video_start_time integer, author_name character varying(255), author_title character varying(255), file uuid);
CREATE TABLE directus.roles (id uuid NOT NULL, sort integer, user_created uuid, date_created timestamp with time zone, user_updated uuid, date_updated timestamp with time zone, simulations uuid, name character varying(255) NOT NULL, writing_style text NOT NULL, title character varying(255), public_description text, key character varying(255) NOT NULL DEFAULT NULL::character varying, playable_character boolean DEFAULT false, avatar uuid, tag character varying(255) DEFAULT NULL::character varying, "group" character varying(255), meta json);
CREATE TABLE directus.sim_tasks (id uuid NOT NULL, status character varying(255) NOT NULL DEFAULT 'draft'::character varying, sort integer, date_created timestamp with time zone, date_updated timestamp with time zone, simulation uuid, title character varying(255), description text, task_type character varying(255), "order" integer, max_call_duration integer DEFAULT 600);
CREATE TABLE directus.sequences (id uuid NOT NULL, sort integer, user_created uuid, date_created timestamp with time zone, user_updated uuid, date_updated timestamp with time zone, simulation uuid, title character varying(255), public_description text, task text, examiner character varying(255) DEFAULT NULL::character varying, asset_type character varying(255), acceptance_checks json, evaluation_checks json, skills json, assets_links json, mission_list json, tasks json, validation_success_threshold integer DEFAULT 80, validation_acceptance_criteria json, validation_evaluation_criteria json, validation_version integer NOT NULL DEFAULT 2, ai_vendor character varying(255) DEFAULT 'azure'::character varying, ai_model character varying(255) DEFAULT 'gpt-5.1'::character varying, sequence_type character varying(255) NOT NULL DEFAULT 'SEQUENCE_TYPE_CONVERSATION'::character varying, validation_features json NOT NULL DEFAULT '["VALIDATION_FEATURES_VALIDATION_REQUIRED","VALIDATION_FEATURES_VALIDATE_WITH_ATTACHMENT"]'::json, intro_video character varying(255), scenario_video uuid, scenario_intro text, qualitative_skills json, evaluation_skills json, voice_engine character varying(255) DEFAULT 'livekitchain'::character varying, run_code boolean DEFAULT false, max_total_call_durations integer DEFAULT 1200);
CREATE TABLE directus.task_checks (id uuid NOT NULL, status character varying(255) NOT NULL DEFAULT 'draft'::character varying, date_created timestamp with time zone, date_updated timestamp with time zone, context text, task uuid, input_format json, input_scope json);
CREATE TABLE directus.task_sub_checks (id uuid NOT NULL, status character varying(255) NOT NULL DEFAULT 'draft'::character varying, date_created timestamp with time zone, date_updated timestamp with time zone, description text, scope character varying(255), engine character varying(255), task_check uuid, success_condition text, fail_condition text);
CREATE TABLE directus.sequences_roles (id integer NOT NULL DEFAULT nextval('directus.sequences_roles_id_seq'::regclass), sequences_id uuid, roles_id uuid, internal_context text, sort integer, stakeholder boolean DEFAULT false, public_description text, date_created timestamp without time zone DEFAULT CURRENT_TIMESTAMP, tasks_guidelines json, engagement_guideline text);

-- The other 17 collections (real prod DDL):
CREATE TABLE directus.curators (id uuid NOT NULL, status character varying(255) NOT NULL DEFAULT 'draft'::character varying, user_created uuid, date_created timestamp with time zone, user_updated uuid, date_updated timestamp with time zone, name character varying(255) NOT NULL, description text, image uuid, job_title character varying(255), linkedin_url character varying(255));
CREATE TABLE directus.email_notifications (id uuid NOT NULL, date_created timestamp with time zone, date_updated timestamp with time zone, type character varying(255), subject character varying(255), body text, preview_text text, jobsimulation uuid);
CREATE TABLE directus.job_position (id uuid NOT NULL, date_created timestamp with time zone, date_updated timestamp with time zone, title character varying(255) NOT NULL DEFAULT NULL::character varying, description text, url character varying(255), tenant_id character varying(255));
CREATE TABLE directus.knowledge_asset (id uuid NOT NULL, date_created timestamp with time zone, date_updated timestamp with time zone, title character varying(255), description text, content text, roles_with_access json, file_name character varying(255), is_player_accessible boolean DEFAULT false, content_type character varying(255), storage_id character varying(255), sequence_id uuid, language character varying(255), exclude_from_roleplay boolean DEFAULT false);
CREATE TABLE directus.languages (code character varying(255) NOT NULL, name character varying(255), direction character varying(255) DEFAULT 'ltr'::character varying);
CREATE TABLE directus.library_categories (id uuid NOT NULL, user_created uuid, date_created timestamp with time zone, user_updated uuid, date_updated timestamp with time zone, name character varying(255) DEFAULT NULL::character varying, library_categories uuid, slug character varying(255), macro_category uuid, description text);
CREATE TABLE directus.library_macro_categories (id uuid NOT NULL, date_created timestamp with time zone, date_updated timestamp with time zone, name character varying(255), slug character varying(255), description text, sort integer);
CREATE TABLE directus.sequences_files (id integer NOT NULL DEFAULT nextval('directus.sequences_files_id_seq'::regclass), sequences_id uuid, directus_files_id uuid);
CREATE TABLE directus.sequences_files_2 (id integer NOT NULL DEFAULT nextval('directus.sequences_files_2_id_seq'::regclass), sequences_id uuid, directus_files_id uuid);
CREATE TABLE directus.sim_features (id uuid NOT NULL, chat boolean DEFAULT true, voice boolean DEFAULT false, code boolean DEFAULT false, doc boolean DEFAULT false, simulation uuid, collaborative_doc boolean DEFAULT false);
CREATE TABLE directus.sim_roles_tasks (id uuid NOT NULL, status character varying(255) NOT NULL DEFAULT 'draft'::character varying, date_created timestamp with time zone, date_updated timestamp with time zone, role uuid, sim_task uuid, need_to_contact_player boolean DEFAULT false, guideline text, engagement_guideline text, interaction_modes json, first_message_guideline text, roleplay_rules text, is_roleplay_rules_enabled boolean DEFAULT false, knowledge_guidelines text);
CREATE TABLE directus.sim_translations (id integer NOT NULL DEFAULT nextval('directus.sim_translations_id_seq'::regclass), language_id character varying(255) DEFAULT 'english'::character varying, translation json, simulation uuid);
CREATE TABLE directus.simulations_extraction (id uuid NOT NULL, date_created timestamp with time zone, date_updated timestamp with time zone, jobsimulation uuid, schema text NOT NULL);
CREATE TABLE directus.simulations_library_categories (id integer NOT NULL DEFAULT nextval('directus.simulations_library_categories_id_seq'::regclass), simulations_id uuid, library_categories_id uuid);
CREATE TABLE directus.simulations_translations (id integer NOT NULL DEFAULT nextval('directus.simulations_translations_id_seq'::regclass), simulations_id uuid, languages_code character varying(255));
CREATE TABLE directus.skill_paths_curators (id integer NOT NULL DEFAULT nextval('directus.skill_paths_curators_id_seq'::regclass), skill_paths_id uuid, curators_id uuid, sort integer);
CREATE TABLE directus.skill_paths_library_categories (id integer NOT NULL DEFAULT nextval('directus.skill_paths_library_categories_id_seq'::regclass), skill_paths_id uuid, library_categories_id uuid);
